import os
import glob
import logging
from typing import List, Dict, Any, Generator

logger = logging.getLogger(__name__)

class Processor:
    """
    Processes cloned repositories:
    - Filters files by extension and ignore patterns
    - Reads content and normalizes it
    - Removes minified or autogenerated files
    """
    
    def __init__(self, include_extensions: List[str] = None, exclude_patterns: List[str] = None):
        """
        Args:
            include_extensions: List of extensions to process (e.g., ['.go', '.sql'])
            exclude_patterns: Substrings that if present in path, file is ignored
        """
        self.include_extensions = include_extensions or ['.go']
        # Default excludes for typical code quality datasets
        self.exclude_patterns = exclude_patterns or [
            "vendor/", "node_modules/", ".git/", "mocks/", "testdata/",
            "_test.go", "mock_", "pb.go", "_string.go"
        ]

    def _should_process_file(self, filepath: str) -> bool:
        """Determines if a file should be processed based on rules."""
        # Check extension
        if not any(filepath.endswith(ext) for ext in self.include_extensions):
            return False
            
        # Check excludes
        filepath_normalized = filepath.replace("\\", "/")
        if any(pattern in filepath_normalized for pattern in self.exclude_patterns):
            return False
            
        return True

    def process_repository(self, repo_path: str) -> Generator[Dict[str, str], None, None]:
        """
        Walks a repository and yields dicts of file content.
        """
        if not os.path.exists(repo_path):
            logger.warning(f"Repository path does not exist: {repo_path}")
            return
            
        repo_name = os.path.basename(repo_path)
        logger.info(f"Processing repository: {repo_name}")
        
        processed_count = 0
        skipped_count = 0
        
        for root, dirs, files in os.walk(repo_path):
            for file in files:
                filepath = os.path.join(root, file)
                rel_path = os.path.relpath(filepath, repo_path)
                
                if not self._should_process_file(rel_path):
                    skipped_count += 1
                    continue
                    
                try:
                    with open(filepath, 'r', encoding='utf-8') as f:
                        content = f.read()
                        
                    # Basic heuristic: ignore empty files or massive autogenerated files
                    if not content.strip() or len(content) > 1000000:
                        skipped_count += 1
                        continue
                        
                    processed_count += 1
                    yield {
                        "repo": repo_name,
                        "file_path": rel_path,
                        "content": content
                    }
                except UnicodeDecodeError:
                    skipped_count += 1
                    logger.debug(f"Skipping binary/non-utf8 file: {rel_path}")
                except Exception as e:
                    skipped_count += 1
                    logger.debug(f"Error reading {rel_path}: {e}")
                    
        logger.info(f"Finished processing {repo_name}: extracted {processed_count} files, skipped {skipped_count}.")

# Example usage
if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')
    
    processor = Processor()
    # Test on the chi repo downloaded earlier
    test_path = "data/raw_test/go-chi_chi"
    
    if os.path.exists(test_path):
        files_data = list(processor.process_repository(test_path))
        print(f"Extracted {len(files_data)} valid Go files from go-chi/chi.")
        if files_data:
            print(f"Sample file: {files_data[0]['file_path']}")
            print(f"Sample content length: {len(files_data[0]['content'])} chars")
    else:
        print(f"Test path {test_path} not found. Run downloader.py first.")
